# -*- coding: utf-8 -*-
"""PrimeNumbersInNatural_Squares_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Usd7iKwiNOERVJTDvdKZeRNQBZDYPv0C
"""



A = int(input("Choose A: "))
B = int(input("Choose B: "))
SOMA = 0
NUM = 0
while A <= B:
 SOMA = SOMA + A**2
 if(A**2 >= 0):
   print(A**2, " It's natural.")
   NUM = NUM + 1
 A = A + 1
print("The sum of the sequence is: ", SOMA)
print( NUM," n squares of the first n natural numbers were read.")